go mod init github.com/pburskey/hasd_covid
go get -u github.com/gomodule/redigo
go get -u github.com/go-redis/redis
go get -u github.com/jinzhu/gorm
go get -u github.com/go-sql-driver/mysql
go get -u github.com/jinzhu/gorm/dialects/mysql
go get -u github.com/rs/cors
go get -u github.com/go-sql-driver/mysql
go get -u github.com/gorilla/mux
go get -u github.com/olekukonko/tablewriter