version: "3.7"
services:

  redis:
    image: redis:latest
    command: redis-server --requirepass letmein

    ports:
      - "6379:6379"

    volumes:
      - "./config/redis/redis-data:/var/lib/redis"
      - "./config/redis/redis.conf:/usr/local/etc/redis/redis.conf"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hasd_covid'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'letmein'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
#      - mysql:/var/lib/mysql
      - "./scripts/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/mysql/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./scripts/mysql/validation.sql:/docker-entrypoint-initdb.d/3.sql"

volumes:
  mysql:
